name: Go
on: push
env:
  DEBUG: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
          - "1.25"
          - "1.26"
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: go test -cover -race ./...
